# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Python\Lessons\Code\实战开发02-PyQt5实用工具\ui\chat_room_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatRoomDialog(object):
    def setupUi(self, ChatRoomDialog):
        ChatRoomDialog.setObjectName("ChatRoomDialog")
        ChatRoomDialog.resize(714, 555)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(ChatRoomDialog)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.edit_recv = QtWidgets.QPlainTextEdit(ChatRoomDialog)
        self.edit_recv.setObjectName("edit_recv")
        self.verticalLayout_4.addWidget(self.edit_recv)
        self.edit_send = QtWidgets.QTextEdit(ChatRoomDialog)
        self.edit_send.setObjectName("edit_send")
        self.verticalLayout_4.addWidget(self.edit_send)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_close = QtWidgets.QPushButton(ChatRoomDialog)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_2.addWidget(self.btn_close)
        self.btn_send = QtWidgets.QPushButton(ChatRoomDialog)
        self.btn_send.setObjectName("btn_send")
        self.horizontalLayout_2.addWidget(self.btn_send)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.setStretch(0, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(ChatRoomDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.edit_notify = QtWidgets.QTextEdit(self.groupBox)
        self.edit_notify.setMaximumSize(QtCore.QSize(160, 16777215))
        self.edit_notify.setObjectName("edit_notify")
        self.verticalLayout.addWidget(self.edit_notify)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(ChatRoomDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lv_members = QtWidgets.QListView(self.groupBox_2)
        self.lv_members.setMaximumSize(QtCore.QSize(160, 16777215))
        self.lv_members.setObjectName("lv_members")
        self.verticalLayout_2.addWidget(self.lv_members)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout)

        self.retranslateUi(ChatRoomDialog)
        QtCore.QMetaObject.connectSlotsByName(ChatRoomDialog)

    def retranslateUi(self, ChatRoomDialog):
        _translate = QtCore.QCoreApplication.translate
        ChatRoomDialog.setWindowTitle(_translate("ChatRoomDialog", "Dialog"))
        self.btn_close.setText(_translate("ChatRoomDialog", "关闭"))
        self.btn_send.setText(_translate("ChatRoomDialog", "发送"))
        self.groupBox.setTitle(_translate("ChatRoomDialog", "群公告："))
        self.groupBox_2.setTitle(_translate("ChatRoomDialog", "群成员："))
