# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat_rooms_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatRoomsWidget(object):
    def setupUi(self, ChatRoomsWidget):
        ChatRoomsWidget.setObjectName("ChatRoomsWidget")
        ChatRoomsWidget.resize(950, 662)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ChatRoomsWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listView = QtWidgets.QListView(ChatRoomsWidget)
        self.listView.setObjectName("listView")
        self.horizontalLayout.addWidget(self.listView)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_join = QtWidgets.QPushButton(ChatRoomsWidget)
        self.btn_join.setAutoDefault(False)
        self.btn_join.setDefault(False)
        self.btn_join.setFlat(False)
        self.btn_join.setObjectName("btn_join")
        self.verticalLayout.addWidget(self.btn_join)
        self.btn_create = QtWidgets.QPushButton(ChatRoomsWidget)
        self.btn_create.setObjectName("btn_create")
        self.verticalLayout.addWidget(self.btn_create)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(ChatRoomsWidget)
        QtCore.QMetaObject.connectSlotsByName(ChatRoomsWidget)

    def retranslateUi(self, ChatRoomsWidget):
        _translate = QtCore.QCoreApplication.translate
        ChatRoomsWidget.setWindowTitle(_translate("ChatRoomsWidget", "Form"))
        self.btn_join.setText(_translate("ChatRoomsWidget", "加入聊天室"))
        self.btn_create.setText(_translate("ChatRoomsWidget", "创建聊天室"))
