# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Python\Lessons\Code\06_上位机开发PyQt5\ui\my_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyWidget(object):
    def setupUi(self, MyWidget):
        MyWidget.setObjectName("MyWidget")
        MyWidget.resize(530, 415)
        self.btn_send = QtWidgets.QPushButton(MyWidget)
        self.btn_send.setGeometry(QtCore.QRect(180, 80, 75, 23))
        self.btn_send.setCheckable(True)
        self.btn_send.setObjectName("btn_send")

        self.retranslateUi(MyWidget)
        QtCore.QMetaObject.connectSlotsByName(MyWidget)

    def retranslateUi(self, MyWidget):
        _translate = QtCore.QCoreApplication.translate
        MyWidget.setWindowTitle(_translate("MyWidget", "黑马窗口标题"))
        self.btn_send.setText(_translate("MyWidget", "按钮"))
